ruby:
  config_file: .rubocop.yml

haml:
  config_file: .haml-lint.yml

slim_lint:
  config_file: .slim-lint.yml

scss:
  config_file: .scss-lint.yml

credo:
  enabled: true

jshint:
  config_file: .jshintrc
